package interfaces;

import businesslogicclient.Authenticated;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import javax.swing.JOptionPane;

/**
 * Represents the home page graphical user interface.
 * @author Diogo Recharte
 */
public class HomePageGUI extends javax.swing.JPanel {

    /**
     * Class Constructor.
     * <p>
     * Initialises all the components used in the HomePage GUI.
     */
    public HomePageGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bashipLabel = new javax.swing.JLabel();
        adsPanel = new javax.swing.JPanel();
        adsLabel = new javax.swing.JLabel();
        playNowButton = new javax.swing.JButton();
        challengeButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(220, 220, 225));

        bashipLabel.setBackground(new java.awt.Color(220, 220, 225));
        bashipLabel.setFont(new java.awt.Font("Tahoma", 1, 120)); // NOI18N
        bashipLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bashipLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/ship-large-plus.png"))); // NOI18N
        bashipLabel.setText(" BaShip");

        adsLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        adsLabel.setText("Ads");

        javax.swing.GroupLayout adsPanelLayout = new javax.swing.GroupLayout(adsPanel);
        adsPanel.setLayout(adsPanelLayout);
        adsPanelLayout.setHorizontalGroup(
            adsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adsPanelLayout.createSequentialGroup()
                .addContainerGap(431, Short.MAX_VALUE)
                .addComponent(adsLabel)
                .addGap(431, 431, 431))
        );
        adsPanelLayout.setVerticalGroup(
            adsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adsPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(adsLabel)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        playNowButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        playNowButton.setText("Play Now");
        playNowButton.setOpaque(false);
        playNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playNowButtonActionPerformed(evt);
            }
        });

        challengeButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        challengeButton.setText("Challenge");
        challengeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                challengeButtonActionPerformed(evt);
            }
        });

        settingsButton.setBackground(new java.awt.Color(220, 220, 225));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/settings.png"))); // NOI18N
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addComponent(adsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(bashipLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(483, 483, 483)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(playNowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(challengeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(settingsButton)
                    .addComponent(bashipLabel))
                .addGap(81, 81, 81)
                .addComponent(playNowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(challengeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(adsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void playNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playNowButtonActionPerformed
        MainFrame.changeInterface(MainFrame.LOADING);
        ExecutorService executor = Executors.newCachedThreadPool();
        executor.submit(new Runnable(){
            @Override
            public void run() {
                if(Authenticated.playGame()){
                    MainFrame.changeInterface(MainFrame.PLACESHIPS);
                }
                else{
                    MainFrame.changeInterface(MainFrame.HOME);
                    JOptionPane.showMessageDialog(HomePageGUI.this, "Couldn't find game", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            
        });
        executor.shutdown();
    }//GEN-LAST:event_playNowButtonActionPerformed

    private void challengeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challengeButtonActionPerformed
        MainFrame.changeInterface(MainFrame.CHALLENGE);
    }//GEN-LAST:event_challengeButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        MainFrame.changeInterface(MainFrame.SETTINGS);
    }//GEN-LAST:event_settingsButtonActionPerformed

    @Override
    public void paintComponent(Graphics g) {
    super.paintComponent(g);

    // Draw the background image.
    g.drawImage(MainFrame.getBackgroundImage(), 0, 0, this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adsLabel;
    private javax.swing.JPanel adsPanel;
    private javax.swing.JLabel bashipLabel;
    private javax.swing.JButton challengeButton;
    private javax.swing.JButton playNowButton;
    private javax.swing.JButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
